### ISSUE TITLE
Is there a way to read and write at the same time

### ISSUE THREAD

**Issue by marc2332** [andfoy/winpty-rs#39]
Is there a way to read and write at the same time? I am currently wrapping the pty instance like `Arc<Mutex<PTY>>` so I can move around the PTY, but I still can't read and write at the same since there can obviously only be one mutex guard. So, I think it would be super useful to have some kind `.split()` method or something similar that returns a Writer and a Reader that can be used at the same time.

Thoughts?

**Comment by andfoy** [comment]
@marc2332, by default, the PTY object allows for concurrent and parallel access, since the input/output pipes are independent of each other. The best way is to spawn a thread that blocks on the call to `read()` and let the main thread write to the PTY. 

When a thread is "asleep" it does not consume any CPU resources, as opposed to continuously calling `read()` on a non-blocking fashion. From your use-case, it seems that you need to modify your frontend in order to be concurrent, so that the reading thread sends the characters each time `read()` returns, it is important to note here that you don't need to write the characters that are sent to the pty via `write()`, since those will be returned by `read()`

**Comment by andfoy** [comment]
PyWinPTY does this as follows: https://github.com/andfoy/pywinpty/blob/2f2733196e0e93fa461bb4e953b19be1d95eeaa4/winpty/ptyprocess.py#L345

**Comment by marc2332** [comment]
@andfoy Thanks! Removing the Mutex actually made a huge difference. It's now so much faster, although not as good I would want (But I am sure that's just my fault too).

Thank you 💖
